<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  year18[
<!ELEMENT year18 (IMAGE*)>

<!ELEMENT IMAGE (IMAGESRC, STYLE)>
<!ELEMENT IMAGESRC (#PCDATA)>
<!ELEMENT STYLE (#PCDATA)>
]>

<year18>

  <IMAGE>
    <IMAGESRC>2018_19/r1c1.png</IMAGESRC>
    <STYLE>float:left;margin-bottom:-10%</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r1c2.png</IMAGESRC>
    <STYLE>float:left;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r1c3.png</IMAGESRC>
    <STYLE>float:left;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r1c4.png</IMAGESRC>
    <STYLE>float:left;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r1c5.png</IMAGESRC>
    <STYLE>;</STYLE>
  </IMAGE>



  <IMAGE>
    <IMAGESRC>2018_19/r2c1.png</IMAGESRC>
    <STYLE>float:left;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r2c2.png</IMAGESRC>
    <STYLE>float:left; margin-top:-10%;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r2c3.png</IMAGESRC>
    <STYLE>float:left; margin-top:-10%;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r2c4.png</IMAGESRC>
    <STYLE>margin-top:-10%;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r2c5.png</IMAGESRC>
    <STYLE>float:right;margin-top:0%;margin-right:3.4%;</STYLE>
  </IMAGE>



  <IMAGE>
    <IMAGESRC>2018_19/r3c4.png</IMAGESRC>
    <STYLE>float:;margin-left:0%</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r3c2.png</IMAGESRC>
    <STYLE>float:left;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r3c3.png</IMAGESRC>
    <STYLE>float:left;margin-top:-10%;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r3c1.png</IMAGESRC>
    <STYLE>margin-top:-16.5%;margin-right:2.7%;</STYLE>
  </IMAGE>

  <IMAGE>
    <IMAGESRC>2018_19/r3c5.png</IMAGESRC>
    <STYLE>float:right;margin-top:-15.2%;margin-right:3.4%;</STYLE>
  </IMAGE>

</year18>
